language: ruby
rvm:
- 2.3.5
script:
  - bundle exec rake db:migrate && bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: d2e3d422-dc4d-4550-8665-0d8548e56dc0
  app: applpa2
  run: "rake db:migrate"
